language: node_js
node_js:
  - '4'
sudo: required
cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache
matrix:
  fast_finish: true
before_install:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version
  - npm install -g codeclimate-test-reporter
install:
  - npm install
  - bower install
script:
  - 'COVERAGE=true ember try:each'
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  code_climate:
    repo_token: 6617c284452df738ac3e8225433c9ce4d19bb2a151d542fffb39bd04535d12b2
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
