---
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "6.1"

sudo: required

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

env:
  # we recommend testing LTS's and latest stable release (bonus points to beta/canary)
  - EMBER_TRY_SCENARIO=ember-lts-2.4
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install -g codeclimate-test-reporter

install:
  - npm install
  - bower install

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  # - COVERAGE=true ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
  - ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup

dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  code_climate:
    repo_token: 6617c284452df738ac3e8225433c9ce4d19bb2a151d542fffb39bd04535d12b2

#after_script:
#  - codeclimate-test-reporter < coverage/lcov.info
